[build]
  base = "workspaces/web"
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"

# Configurações para variáveis de ambiente do Sanity
# Certifique-se de adicionar essas variáveis no painel do Netlify:
# NEXT_PUBLIC_SANITY_PROJECT_ID
# NEXT_PUBLIC_SANITY_DATASET
# NEXT_PUBLIC_SANITY_API_VERSION
# SANITY_API_READ_TOKEN (se necessário)
